# Generated by Django 5.2 on 2025-05-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
